TARGET = iphone:clang:latest:7.0
INSTALL_TARGET_PROCESSES = norwagov

include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = norwagov

norwagov_FILES = AppDelegate.swift RootViewController.swift
norwagov_FRAMEWORKS = UIKit CoreGraphics

include $(THEOS_MAKE_PATH)/application.mk
